// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iimwhhcyqlhuqpnpdsem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpbXdoaGN5cWxodXFwbnBkc2VtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NTExMTEsImV4cCI6MjA2ODMyNzExMX0.58ubYZENnYzD68Fb5w0Ha0l5YzbciyOqFbzlPyT_ojg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});